# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60425b1a10b82f264c84e48790110a816c1b46bd2625eb385bd6b4298a9c23a71c5f98efad018cea81c0d53b8c1889ea1d78361b9c727b3694406fe0c0644640

test:
  secret_key_base: 74eae29ace61247f715708c04b3769cb36b7588080852431e31f07f9254b5fb9d569136ef2409259062cfb1f3044dda912d5ec222925c5d4e4861a8e72f7b8da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
